# Generated by Django 5.0.4 on 2024-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'Вспомогательный сервис', 'verbose_name_plural': 'Вспомогательные сервисы'},
        ),
        migrations.AddField(
            model_name='subservice',
            name='price',
            field=models.CharField(default='', max_length=254),
        ),
    ]
