# Generated by Django 5.0.4 on 2024-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_subservice_options_subservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='info_d',
            field=models.TextField(max_length=500),
        ),
    ]
