# Generated by Django 5.0.4 on 2024-05-01 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='subservice_time',
            field=models.TimeField(default=datetime.datetime.utcnow),
        ),
    ]
