# Generated by Django 5.0.4 on 2024-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_statusappointment_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='service_doctor',
            field=models.ManyToManyField(to='appointments.service'),
        ),
    ]
