# Generated by Django 5.0.4 on 2024-05-01 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_subservice_subservice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='duration_minutes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
