# Generated by Django 5.0.4 on 2024-05-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_subservice_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name_p',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name_p',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number_p',
            field=models.CharField(default=datetime.datetime.now, max_length=13),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
