# Generated by Django 5.0.4 on 2024-05-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.statusappointment'),
        ),
    ]
