# Generated by Django 5.0.4 on 2024-05-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointment_medical_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='duration_minutes',
        ),
    ]
