# Generated by Django 5.0.4 on 2024-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number_p',
            field=models.CharField(max_length=9),
        ),
    ]
