# Generated by Django 5.0.4 on 2024-05-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_remove_doctors_service_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.doctors'),
        ),
    ]
