# Generated by Django 5.0.4 on 2024-05-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_alter_appointment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='appointments.doctors'),
        ),
    ]
