# Generated by Django 5.0.4 on 2024-05-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_alter_appointment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.service'),
        ),
    ]
