# Generated by Django 5.0.4 on 2024-05-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_alter_subservice_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.statusappointment'),
        ),
    ]
